In [2]:
import pickle
import numpy as np
import cv2
import time
from sklearn.model_selection import train_test_split

In [3]:
#with open('./trainingdata.pickle', 'rb') as fr:
with open('./trainingdata_add2.pickle', 'rb') as fr:
    data = pickle.load(fr)

In [4]:
n_images = len(data)
n_images

1131

In [5]:
#test, training = data[0:int(n_images/3)], data[int(n_images/3):]
training, test = train_test_split(data, test_size=0.33, random_state=747)

In [6]:
#cv2.namedWindow('disp')
for direcao,velocidade,img in data:
    img = np.array(img,dtype=np.uint8)
    print (direcao, img)
    #cv2.imshow('disp',np.array(cv2.resize(img,(280,280))))

0.0 [[  0   0   0   0   0   0   0 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255 255   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255 255 255 255 255 255 255]
 [  0   0   0   0   0   0   0 255 255 255 255 255 255 255 255 255]
 [  0   0   0   0   0   0   0   0 255 255 255 255   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0 

 [  0   0   0   0   0   0 255 255 255   0   0   0   0   0   0   0]]
0.5 [[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0 255 255 255]
 [  0   0   0   0   0   0   0   0   0   0   0   0 255 255 255   0]
 [  0   0   0   0   0   0   0   0   0   0 255 255 255 255   0   0]
 [  0   0   0   0   0   0   0   0   0 255 255 255   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0 255 255 255   0   0   0   0]
 [  0   0   0   0   0   0   0   0 255 255 255   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255 255   0   0   0   0   0

 [  0   0   0   0   0   0   0   0   0   0 255 255 255   0   0   0]]
0.0 [[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [255 255   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0 255 255 255 255   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 255 255 255   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0 255 255   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0 255 255 255   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0 255 255   0   0

 [  0   0   0   0   0   0 255 255 255   0   0   0   0   0   0   0]]
0.0 [[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0 255 255]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0 255 255 255]
 [  0   0   0   0   0   0   0   0   0   0   0   0 255 255 255   0]
 [  0   0   0   0   0   0   0   0   0   0   0 255 255 255   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0 255 255   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0 255 255 255   0   0   0]
 [  0   0   0   0   0   0   0   0   0 255 255 255   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0 255 255   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 255 255 255   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255   0   0   0   0

 [  0   0   0   0   0 255 255 255   0   0   0   0   0   0   0   0]]
0.0 [[  0   0   0   0   0   0   0   0 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255   0   0   0   0   0   0

 [  0   0   0   0   0 255 255 255   0   0   0   0   0   0   0   0]]
1.0 [[  0 255 255 255 255 255 255 255 255 255 255 255 255 255 255 255]
 [  0 255 255 255 255 255 255 255 255 255 255   0   0   0   0   0]
 [  0 255 255 255   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 255]
 [  0   0   0   0   0   0   0   0   0   0   0 255 255 255 255 255]
 [  0   0   0   0   0   0   0   0   0 255 255 255 255   0   0   0]
 [  0   0   0   0   0   0   0   0 255 255 255   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0 255 255 255   0   0   0   0   0   0

 [  0   0   0   0   0   0 255 255 255   0   0   0   0   0   0   0]]
1.0 [[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 255]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0 255 255 255]
 [  0   0   0   0   0   0   0   0   0   0   0   0 255 255 255   0]
 [  0   0   0   0   0   0   0   0   0   0   0 255 255 255   0   0]
 [  0   0   0   0   0   0   0   0   0   0   0 255 255   0   0   0]
 [  0   0   0   0   0   0   0   0   0   0 255 255 255   0   0   0]
 [  0   0   0   0   0   0   0   0   0 255 255 255   0   0   0   0]
 [  0   0   0   0   0   0   0   0 255 255 255   0   0   0   0   0]
 [  0   0   0   0   0   0   0   0 255 255 255   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255   0   0   0   0   0   0]
 [  0   0   0   0   0   0   0 255 255 255   0   0   0   0

 [  0   0 255 255 255 255   0   0   0   0   0   0   0   0   0   0]]
0.5 [[  0   0   0   0   0   0   0 255 255   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0   0 255 255   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0 255 255   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0 255 255   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0   0 255 255   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 255 255   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0   0 255 255   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 255 255 255   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 255 255 255   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 255 255   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 255 255   0   0   0   0   0   0   0   0   0   0   0]
 [  0   0   0 255 255   0   0   0   0   0   0   0   0   0

In [6]:
type(data[0][2])

numpy.ndarray

In [11]:
data[0][2] , data[1][2]

(array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0],
        [ 

In [8]:
data[0:2]

[(0,
  0,
  array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
            0,   0,   0],
         [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
      

In [9]:
type(data[0])

tuple

In [10]:
type(data)

list